version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env

    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbit_data_container:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbit_data_container:
  mongodb_data_container:
